CREATE PROCEDURE [dbo].[SP_ComcdList]
                 @P_CATEGORY   VARCHAR(50) 
				,@P_CD_ID      VARCHAR(50)

AS

SET NOCOUNT ON;

------//프로시져 내부 변수정의//------
DECLARE @ERR_PGM        VARCHAR(50)   = 'SP_ComcdList';
DECLARE @Err_Msg        VARCHAR(300); 
DECLARE @Err_CD         VARCHAR(20); 
DECLARE @Err_TP         VARCHAR(10); 
DECLARE @ERR_LINE       NUMERIC(10,0); 
DECLARE @ERR_NUMBER     NUMERIC(10,0);
DECLARE @REMARK         VARCHAR(20);

DECLARE @DELETE_CNT     NUMERIC(10) = 0;
DECLARE @INSERT_CNT     NUMERIC(10) = 0;
DECLARE @UPDATE_CNT     NUMERIC(10) = 0;

DECLARE @SQL            NVARCHAR(4000)
DECLARE @CUR_DATE       VARCHAR(8);
DECLARE @BEF_DATE       DATETIME;

DECLARE @CD_ID          VARCHAR(22);
DECLARE @CD_NM          VARCHAR(100);
DECLARE @COLUMNA        VARCHAR(100);
DECLARE @COLUMN1        NUMERIC(15,5);
DECLARE @TMP1           VARCHAR(100);
DECLARE @TMP2           VARCHAR(100);




BEGIN

  SELECT  CONVERT(VARCHAR, ROW_NUMBER() OVER (ORDER BY SORT_SEQ ASC)) AS L_NUM 
         ,CD_ID 
         ,CD_NM
  FROM    TB_CM_COM_CD 
  WHERE   CATEGORY = @P_CATEGORY
  AND     CD_ID LIKE @P_CD_ID +'%'
  AND     USE_YN   = 'Y'
  ORDER   BY SORT_SEQ, CD_ID;
    
END
