CREATE TABLE [dbo].[TB_CM_MENU] (
    [MENU_ID]    VARCHAR (10) NOT NULL,
    [MENU_NM]    VARCHAR (50) NULL,
    [UP_MENU_ID] VARCHAR (10) NULL,
    [SCR_ID]     VARCHAR (40) NULL,
    [MENU_SEQ]   NUMERIC (4)  NULL,
    [REGISTER]   VARCHAR (20) NULL,
    [REG_DDTT]   DATETIME     NULL,
    [MODIFIER]   VARCHAR (20) NULL,
    [MOD_DDTT]   DATETIME     NULL,
    CONSTRAINT [PK_TB_CM_MENU] PRIMARY KEY CLUSTERED ([MENU_ID] ASC)
);

