CREATE TABLE [dbo].[TB_CM_ERR_LOG] (
    [SEQ_NO]   NUMERIC (22)  NOT NULL,
    [PGM_ID]   VARCHAR (50)  NULL,
    [ERR_CD]   VARCHAR (20)  NULL,
    [ERR_TP]   VARCHAR (10)  NULL,
    [ERR_MSG]  VARCHAR (300) NULL,
    [REG_DDTT] DATETIME      NULL,
    [REGISTER] VARCHAR (20)  NULL,
    CONSTRAINT [PK_TB_CM_ERR_LOG] PRIMARY KEY CLUSTERED ([SEQ_NO] ASC)
);

