CREATE TABLE [dbo].[TB_CM_ACL_GRP] (
    [ACL_GRP_ID] VARCHAR (20) NOT NULL,
    [ACL_GRP_NM] VARCHAR (50) NULL,
    [REMARKS]    VARCHAR (50) NULL,
    [REGISTER]   VARCHAR (20) NULL,
    [REG_DDTT]   DATETIME     NULL,
    [MODIFIER]   VARCHAR (20) NULL,
    [MOD_DDTT]   DATETIME     NULL,
    CONSTRAINT [PK_TB_CM_ACL_GRP] PRIMARY KEY CLUSTERED ([ACL_GRP_ID] ASC)
);

