CREATE TABLE [dbo].[TB_CM_USER] (
    [USER_ID]     VARCHAR (10)  NOT NULL,
    [NM]          VARCHAR (20)  NULL,
    [PASSWD]      VARCHAR (128) NULL,
    [DEPT_CD]     VARCHAR (50)  NULL,
    [POST_CD]     VARCHAR (20)  NULL,
    [INCHRG_LINE] VARCHAR (10)  NULL,
    [TEL_NO]      VARCHAR (13)  NULL,
    [MAIL_ID]     VARCHAR (50)  NULL,
    [ACL_GRP_ID]  VARCHAR (10)  NULL,
    [REGISTER]    VARCHAR (20)  NULL,
    [REG_DDTT]    DATETIME      NULL,
    [MODIFIER]    VARCHAR (20)  NULL,
    [MOD_DDTT]    DATETIME      NULL,
    CONSTRAINT [PK_TB_CM_USER] PRIMARY KEY CLUSTERED ([USER_ID] ASC)
);

