CREATE TABLE [dbo].[TB_CM_SCR] (
    [SCR_ID]   VARCHAR (10) NOT NULL,
    [BIZ_GP]   VARCHAR (2)  NULL,
    [SCR_NM]   VARCHAR (50) NULL,
    [PAGE_ID]  VARCHAR (50) NULL,
    [USE_YN]   VARCHAR (1)  NULL,
    [REGISTER] VARCHAR (20) NULL,
    [REG_DDTT] DATETIME     NULL,
    [MODIFIER] VARCHAR (20) NULL,
    [MOD_DDTT] DATETIME     NULL,
    CONSTRAINT [PK_TB_CM_SCR] PRIMARY KEY CLUSTERED ([SCR_ID] ASC)
);

