CREATE TABLE [dbo].[TB_CM_SCR_USEHIS] (
    [USE_DDTT]     DATETIME     NOT NULL,
    [USER_ID]      VARCHAR (10) NOT NULL,
    [SCR_ID]       VARCHAR (10) NOT NULL,
    [USE_DATE_SEQ] NUMERIC (8)  NOT NULL,
    [BTN_GP]       VARCHAR (1)  NULL,
    [REGISTER]     VARCHAR (20) NULL,
    [REG_DDTT]     DATETIME     NULL,
    CONSTRAINT [PK_TB_CM_SCR_USEHIS] PRIMARY KEY CLUSTERED ([USE_DDTT] ASC, [USER_ID] ASC, [SCR_ID] ASC, [USE_DATE_SEQ] ASC)
);

