CREATE TABLE [dbo].[TB_CM_COM_CD_GRP] (
    [CATEGORY]    VARCHAR (30) NOT NULL,
    [CATEGORY_NM] VARCHAR (40) NULL,
    [USE_YN]      VARCHAR (1)  NULL,
    [REGISTER]    VARCHAR (20) NULL,
    [REG_DDTT]    DATETIME     NULL,
    [MODIFIER]    VARCHAR (20) NULL,
    [MOD_DDTT]    DATETIME     NULL,
    [L3_CATEGORY] VARCHAR (30) NULL,
    CONSTRAINT [PK_TB_CM_COM_CD_GRP] PRIMARY KEY CLUSTERED ([CATEGORY] ASC)
);

