CREATE TABLE [dbo].[TB_CM_UOM_WGT] (
    [ITEM]         VARCHAR (2)     NOT NULL,
    [ITEM_SIZE]    VARCHAR (4)     NOT NULL,
    [STEEL_TYPE]   VARCHAR (3)     NOT NULL,
    [UOM_WGT]      NUMERIC (12, 5) NULL,
    [ITEM_NM]      VARCHAR (50)    NULL,
    [ITEM_SIZE_NM] VARCHAR (50)    NULL,
    [REGISTER]     VARCHAR (20)    NULL,
    [REG_DDTT]     DATETIME        NULL,
    [MODIFIER]     VARCHAR (20)    NULL,
    [MOD_DDTT]     DATETIME        NULL,
    CONSTRAINT [PK_TB_CM_UOM_WGT] PRIMARY KEY CLUSTERED ([ITEM] ASC, [ITEM_SIZE] ASC, [STEEL_TYPE] ASC)
);

