CREATE TABLE [dbo].[TB_CM_LOGINHIS] (
    [LOGIN_DDTT] DATETIME     NOT NULL,
    [USER_ID]    VARCHAR (10) NOT NULL,
    [PC_IP]      VARCHAR (15) NULL,
    [REGISTER]   VARCHAR (20) NULL,
    [REG_DDTT]   DATETIME     NULL,
    CONSTRAINT [PK_TB_CM_LOGINHIS] PRIMARY KEY CLUSTERED ([LOGIN_DDTT] ASC, [USER_ID] ASC)
);

