CREATE TABLE [dbo].[TB_CM_ACL] (
    [ACL_GRP_ID] VARCHAR (20) NOT NULL,
    [SCR_ID]     VARCHAR (10) NOT NULL,
    [INQ_ACL]    VARCHAR (1)  NULL,
    [REG_ACL]    VARCHAR (1)  NULL,
    [MOD_ACL]    VARCHAR (1)  NULL,
    [DEL_ACL]    VARCHAR (1)  NULL,
    [REGISTER]   VARCHAR (20) NULL,
    [REG_DDTT]   DATETIME     NULL,
    [MODIFIER]   VARCHAR (20) NULL,
    [MOD_DDTT]   DATETIME     NULL,
    CONSTRAINT [PK_TB_CM_ACL] PRIMARY KEY CLUSTERED ([ACL_GRP_ID] ASC, [SCR_ID] ASC)
);

