CREATE TABLE [dbo].[TB_DUST_STAT_MGMT] (
    [SHT_DUST_STAT]     VARCHAR (10) NULL,
    [SHT_DUST_ON_DDTT]  DATETIME     NULL,
    [SHT_DUST_OFF_DDTT] DATETIME     NULL,
    [GRD_DUST_STAT]     VARCHAR (10) NULL,
    [GRD_DUST_ON_DDTT]  DATETIME     NULL,
    [GRD_DUST_OFF_DDTT] DATETIME     NULL
);

