CREATE TABLE [dbo].[TB_ELEC_USE_WR] (
    [WORK_DATE]               VARCHAR (8)  NOT NULL,
    [SHT_DUST_DAY_USE_QTY]    NUMERIC (12) NULL,
    [GRD_DUST_DAY_USE_QTY]    NUMERIC (12) NULL,
    [GRD_DAY_USE_QTY]         NUMERIC (12) NULL,
    [FACTORY_ALL_DAY_USE_QTY] NUMERIC (12) NULL,
    [SHT_DUST_TOT_USE_QTY]    NUMERIC (12) NULL,
    [GRD_DUST_TOT_USE_QTY]    NUMERIC (12) NULL,
    [GRD_TOT_USE_QTY]         NUMERIC (12) NULL,
    [FACTORY_ALL_TOT_USE_QTY] NUMERIC (12) NULL,
    [REGISTER]                VARCHAR (20) NULL,
    [REG_DDTT]                DATETIME     NULL,
    [MODIFIER]                VARCHAR (20) NULL,
    [MOD_DDTT]                DATETIME     NULL,
    CONSTRAINT [PK_TB_ELEC_USE_WR] PRIMARY KEY CLUSTERED ([WORK_DATE] ASC)
);

