CREATE TABLE [dbo].[TB_EQP_INFO] (
    [EQP_CD]     VARCHAR (10) NOT NULL,
    [EQP_NM]     VARCHAR (50) NULL,
    [ROUTING_NM] VARCHAR (30) NULL,
    [INST_DATE]  VARCHAR (8)  NULL,
    [REGISTER]   VARCHAR (20) NULL,
    [REG_DDTT]   DATETIME     NULL,
    [MODIFIER]   VARCHAR (20) NULL,
    [MOD_DDTT]   DATETIME     NULL,
    CONSTRAINT [PK_TB_EQP_INFO] PRIMARY KEY CLUSTERED ([EQP_CD] ASC)
);

