CREATE TABLE [dbo].[TB_EQP_CHECK_WR] (
    [EQP_CD]         VARCHAR (10)  NOT NULL,
    [ITEM_CD]        VARCHAR (10)  NOT NULL,
    [CHECK_SEQ]      NUMERIC (10)  NOT NULL,
    [EQP_NM]         VARCHAR (50)  NULL,
    [ROUTING_NM]     VARCHAR (30)  NULL,
    [CHECK_ITEM]     VARCHAR (100) NULL,
    [CHECK_PLN_DATE] VARCHAR (8)   NULL,
    [CHECK_WR_DATE]  VARCHAR (8)   NULL,
    [CHECK_GAP]      NUMERIC (4)   NULL,
    [CHECK_CYCLE]    VARCHAR (5)   NULL,
    [CHECK_YN]       VARCHAR (1)   NULL,
    [CHECK_CNTS]     VARCHAR (100) NULL,
    [USE_CNT]        INT           NULL,
    [PROG_STAT]      VARCHAR (10)  NULL,
    [REGISTER]       VARCHAR (20)  NULL,
    [REG_DDTT]       DATETIME      NULL,
    [MODIFIER]       VARCHAR (20)  NULL,
    [MOD_DDTT]       DATETIME      NULL,
    CONSTRAINT [PK_TB_EQP_CHECK_WR] PRIMARY KEY CLUSTERED ([EQP_CD] ASC, [ITEM_CD] ASC, [CHECK_SEQ] ASC)
);

