CREATE TABLE [dbo].[TB_GRD_WR] (
    [HEAT_NO]               VARCHAR (6)  NOT NULL,
    [HEAT_SEQ]              INT          NOT NULL,
    [REWORK_SNO]            INT          NOT NULL,
    [STEEL]                 VARCHAR (10) NULL,
    [ITEM]                  VARCHAR (2)  NULL,
    [ITEM_SIZE]             VARCHAR (4)  NULL,
    [STEEL_TYPE]            VARCHAR (3)  NULL,
    [MFG_DATE]              VARCHAR (8)  NULL,
    [QR_SCAN_INFO]          VARCHAR (16) NULL,
    [WORK_DATE]             VARCHAR (8)  NULL,
    [GRD_START_DDTT]        DATETIME     NULL,
    [GRD_END_DDTT]          DATETIME     NULL,
    [GRD_DRV_MODE]          INT          NULL,
    [WORK_SETV_Top]         VARCHAR (5)  NULL,
    [WORK_SETV_Right]       VARCHAR (5)  NULL,
    [WORK_SETV_Bottom]      VARCHAR (5)  NULL,
    [WORK_SETV_Left]        VARCHAR (5)  NULL,
    [HEIGHT_MV]             INT          NULL,
    [WIDTH_MV]              INT          NULL,
    [LENGTH_MV]             INT          NULL,
    [FACE_PASS_CNT]         INT          NULL,
    [CORN_PASS_CNT]         INT          NULL,
    [RBGW_SPEED_SETV]       INT          NULL,
    [RBGW_ADV_SETV]         INT          NULL,
    [RBGW_DIA_MV]           INT          NULL,
    [RBGW_ENGY_MV]          INT          NULL,
    [RBGW_VIBR_MV]          INT          NULL,
    [ROTANGLE_SETV]         INT          NULL,
    [ROTANGLE_MV]           INT          NULL,
    [GRD_PRES_SURFACE_SETV] INT          NULL,
    [GRD_PRES_ENDP_SETV]    INT          NULL,
    [GRD_PRES_CORN_SETV]    INT          NULL,
    [GRD_PRES_MV]           INT          NULL,
    [TRUCKSPEED_SETV]       INT          NULL,
    [TRUCKSPEED_MV]         INT          NULL,
    [SURFACE_STAT]          VARCHAR (20) NULL,
    [REWORK_YN]             VARCHAR (1)  NULL,
    [SEND_STAT]             VARCHAR (3)  NULL,
    [REGISTER]              VARCHAR (20) NULL,
    [REG_DDTT]              DATETIME     NULL,
    [MODIFIER]              VARCHAR (20) NULL,
    [MOD_DDTT]              DATETIME     NULL,
    CONSTRAINT [PK_TB_GRD_WR] PRIMARY KEY CLUSTERED ([HEAT_NO] ASC, [HEAT_SEQ] ASC, [REWORK_SNO] ASC)
);

