CREATE TABLE [dbo].[TB_GRD_RBGW_MGMT] (
    [GRD_CHIP_START_DDTT]     DATETIME     NULL,
    [GRD_CHIP_END_DDTT]       DATETIME     NULL,
    [GRD_RBGW_CHG_START_DDTT] DATETIME     NULL,
    [GRD_RBGW_CHG_END_DDTT]   DATETIME     NULL,
    [GRD_RBGW_USE_CNT]        INT          NULL,
    [STOP_START_DDTT]         DATETIME     NULL,
    [STOP_END_DDTT]           DATETIME     NULL,
    [GRD_CHIP_REMV_YN]        NVARCHAR (1) NULL,
    [GRD_RBGW_CHG_YN]         NVARCHAR (1) NULL
);



