CREATE TABLE [dbo].[TB_GRD_OPER_INFO] (
    [WORK_DDTT]             DATETIME     NOT NULL,
    [GRD_DRV_MODE]          INT          NULL,
    [HEIGHT_SETV]           INT          NULL,
    [WIDTH_SETV]            INT          NULL,
    [HEIGHT_MV]             INT          NULL,
    [WIDTH_MV]              INT          NULL,
    [LENGTH_MV]             INT          NULL,
    [FACE_PASS_CNT]         INT          NULL,
    [CORN_PASS_CNT]         INT          NULL,
    [WORK_SEQ]              INT          NULL,
    [WORK_Track_NO]         VARCHAR (10) NULL,
    [RBGW_SPEED_SETV]       INT          NULL,
    [RBGW_ADV_SETV]         INT          NULL,
    [RBGW_DIA_MV]           INT          NULL,
    [RBGW_ENGY_MV]          INT          NULL,
    [RBGW_VIBR_MV]          INT          NULL,
    [ROTANGLE_SETV]         INT          NULL,
    [ROTANGLE_MV]           INT          NULL,
    [GRD_PRES_SURFACE_SETV] INT          NULL,
    [GRD_PRES_ENDP_SETV]    INT          NULL,
    [GRD_PRES_CORN_SETV]    INT          NULL,
    [SET_GRD_Force]         INT          NULL,
    [GRD_PRES_MV]           INT          NULL,
    [GRD_MTR_ELEC]          INT          NULL,
    [TRUCKSPEED_SETV]       INT          NULL,
    [TRUCKSPEED_MV]         INT          NULL,
    [GRD_LOC]               VARCHAR (10) NULL,
    [COOL_DOWN_HR_SETV]     INT          NULL,
    [COOL_DOWN_SPEED_SETV]  INT          NULL,
    [BELT_SLIP_WARN_SETV]   INT          NULL,
    [CORN_GRD_3TRK1bs]      INT          NULL,
    [CORN_GRD_3TRK2bs]      INT          NULL,
    [CORN_GRD_3TRK3fs]      INT          NULL,
    [CORN_GRD_5TRK1bs]      INT          NULL,
    [CORN_GRD_5TRK2bs]      INT          NULL,
    [CORN_GRD_5TRK3bs]      INT          NULL,
    [CORN_GRD_5TRK4fs]      INT          NULL,
    [CORN_GRD_5TRK5fs]      INT          NULL,
    [OutsIDe_back]          INT          NULL,
    [OutsIDe_front]         INT          NULL,
    [WORK_SETV_Top]         VARCHAR (5)  NULL,
    [WORK_SETV_Right]       VARCHAR (5)  NULL,
    [WORK_SETV_Bottom]      VARCHAR (5)  NULL,
    [WORK_SETV_Left]        VARCHAR (5)  NULL,
    [REGISTER]              VARCHAR (20) NULL,
    [REG_DDTT]              DATETIME     NULL,
    [MODIFIER]              VARCHAR (20) NULL,
    [MOD_DDTT]              DATETIME     NULL,
    CONSTRAINT [PK_TB_GRD_OPER_INFO] PRIMARY KEY CLUSTERED ([WORK_DDTT] ASC)
);

