CREATE TABLE [dbo].[TB_GRD_DUST_INFO] (
    [WORK_DDTT]                    DATETIME       NOT NULL,
    [DUST_On_TR]                   DATETIME       NULL,
    [DUST_Off_TR]                  DATETIME       NULL,
    [Bag_BEF_STATICP]              NUMERIC (7, 2) NULL,
    [INH_TEMP]                     NUMERIC (6, 1) NULL,
    [Rotary_Valve_NO1_STAT]        INT            NULL,
    [Rotary_Valve_NO1_ABNORM_STAT] INT            NULL,
    [Rotary_Valve_NO2_STAT]        INT            NULL,
    [Rotary_Valve_NO2_ABNORM_STAT] INT            NULL,
    [Rotary_Valve_NO3_STAT]        INT            NULL,
    [Rotary_Valve_NO3_ABNORM_STAT] INT            NULL,
    [Rotary_Valve_NO4_STAT]        INT            NULL,
    [Rotary_Valve_NO4_ABNORM_STAT] INT            NULL,
    [Vibrator_NO1_STAT]            INT            NULL,
    [Vibrator_NO1_ABNORM_STAT]     INT            NULL,
    [Vibrator_NO2_STAT]            INT            NULL,
    [Vibrator_NO2_ABNORM_STAT]     INT            NULL,
    [Vibrator_NO3_STAT]            INT            NULL,
    [Vibrator_NO3_ABNORM_STAT]     INT            NULL,
    [Pulse_Controller_STAT1]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT2]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT3]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT4]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT5]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT6]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT7]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT8]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT9]       NCHAR (10)     NULL,
    [Pulse_Controller_STAT10]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT11]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT12]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT13]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT14]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT15]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT16]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT17]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT18]      NCHAR (10)     NULL,
    [Pulse_Controller_STAT19]      NCHAR (10)     NULL,
    [Popet_Damper_NO1_STAT]        INT            NULL,
    [Popet_Damper_NO2_STAT]        INT            NULL,
    [Popet_Damper_NO3_STAT]        INT            NULL,
    [DEF_PRES_NO1]                 NUMERIC (6, 1) NULL,
    [DEF_PRES_NO2]                 NUMERIC (6, 1) NULL,
    [DEF_PRES_NO3]                 NUMERIC (6, 1) NULL,
    [OPRN_RT]                      NUMERIC (6, 1) NULL,
    [SETV]                         NUMERIC (6, 1) NULL,
    [LOAD_BRG_TEMP]                NUMERIC (6, 1) NULL,
    [H_LOAD_BRG_TEMP]              NUMERIC (6, 1) NULL,
    [IVT_SPEED_SETV]               NUMERIC (6, 1) NULL,
    [LOAD_VIBR]                    NUMERIC (6, 1) NULL,
    [H_LOAD_VIBR]                  NUMERIC (6, 1) NULL,
    [REGISTER]                     VARCHAR (20)   NULL,
    [REG_DDTT]                     DATETIME       NULL,
    [MODIFIER]                     VARCHAR (20)   NULL,
    [MOD_DDTT]                     DATETIME       NULL,
    CONSTRAINT [PK_TB_GRD_DUST_INFO] PRIMARY KEY CLUSTERED ([WORK_DDTT] ASC)
);



