CREATE TABLE [dbo].[TB_MPI_OPER_INFO] (
    [WORK_DDTT]             DATETIME     NOT NULL,
    [CLWTR_PMP1_STAT]       INT          NULL,
    [CLWTR_PMP2_STAT]       INT          NULL,
    [FIL_MTR_STAT]          INT          NULL,
    [CLWTR_PMP_HDR_STAT]    INT          NULL,
    [MAGNET_PMP1_STAT]      INT          NULL,
    [MAGNET_PMP2_STAT]      INT          NULL,
    [STIR_PMP_HDR_STAT]     INT          NULL,
    [Entry_Motor_FWD]       INT          NULL,
    [Entry_Motor_REV]       INT          NULL,
    [Inspection_Motor_FWD]  INT          NULL,
    [Inspection_Motor_REV]  INT          NULL,
    [OPRS_Motor1_STAT]      INT          NULL,
    [OPRS_Motor2_STAT]      INT          NULL,
    [OPRS_Fan_STAT]         INT          NULL,
    [Dark_Room_Hood_Fan]    INT          NULL,
    [Yoke_TRANS_Motor1_FWD] INT          NULL,
    [Yoke_TRANS_Motor1_BWD] INT          NULL,
    [Yoke_TRANS_Motor2_BWD] INT          NULL,
    [Yoke_TRANS_Motor2_FWD] INT          NULL,
    [OPRS_MTR_HDR_STAT]     INT          NULL,
    [OPRS_SUP_HDR_STAT]     INT          NULL,
    [Yoke_MTR_NO1_CURRENT]  INT          NULL,
    [Yoke_MTR_NO2_CURRENT]  INT          NULL,
    [Yoke_MTR_NO3_CURRENT]  INT          NULL,
    [Yoke_MTR_NO4_CURRENT]  INT          NULL,
    [COIL_NO1_2_CURRENT]    INT          NULL,
    [REGISTER]              VARCHAR (20) NULL,
    [REG_DDTT]              DATETIME     NULL,
    [MODIFIER]              VARCHAR (20) NULL,
    [MOD_DDTT]              DATETIME     NULL,
    CONSTRAINT [PK_TB_MPI_OPER_INFO] PRIMARY KEY CLUSTERED ([WORK_DDTT] ASC)
);

