CREATE TABLE [dbo].[TB_PLC_ITEM_MGMT] (
    [SERVICE_NM]   VARCHAR (40)  NOT NULL,
    [TOPIC_NM]     VARCHAR (30)  NOT NULL,
    [ITEM_ADDRESS] VARCHAR (40)  NOT NULL,
    [ITEM_VAL]     VARCHAR (20)  NULL,
    [ITEM_SEQ]     NUMERIC (10)  NULL,
    [DESCRIPTION]  VARCHAR (200) NULL,
    [UPD_DATE]     DATETIME      NULL,
    [PROC_GP]      VARCHAR (30)  NULL,
    CONSTRAINT [PK_TB_PLC_ITEM_MGMT] PRIMARY KEY CLUSTERED ([SERVICE_NM] ASC, [TOPIC_NM] ASC, [ITEM_ADDRESS] ASC)
);

