CREATE TABLE [dbo].[TB_RL_TM_TRACKING] (
    [HEAT_NO]           VARCHAR (6)  NOT NULL,
    [HEAT_SEQ]          INT          NOT NULL,
    [STEEL]             VARCHAR (10) NULL,
    [ITEM]              VARCHAR (2)  NULL,
    [ITEM_SIZE]         VARCHAR (4)  NULL,
    [STEEL_TYPE]        VARCHAR (3)  NULL,
    [MFG_DATE]          VARCHAR (8)  NULL,
    [WORK_DATE]         VARCHAR (8)  NULL,
    [QR_SCAN_INFO]      VARCHAR (16) NULL,
    [SHT_START_DDTT]    DATETIME     NULL,
    [SHT_END_DDTT]      DATETIME     NULL,
    [MPI_START_DDTT]    DATETIME     NULL,
    [MPI_END_DDTT]      DATETIME     NULL,
    [GRD_START_DDTT]    DATETIME     NULL,
    [GRD_END_DDTT]      DATETIME     NULL,
    [ZONE_CD]           VARCHAR (3)  NULL,
    [ZONE_CD_UPD_DDTT]  DATETIME     NULL,
    [BEF_ZONE_CD]       VARCHAR (3)  NULL,
    [BEF_ZONE_UPD_DDTT] DATETIME     NULL,
    [PROG_STAT]         VARCHAR (5)  NULL,
    [BEF_PROG_STAT]     VARCHAR (5)  NULL,
    [HEIGHT_MV]         INT          NULL,
    [WIDTH_MV]          INT          NULL,
    [LENGTH_MV]         INT          NULL,
    [REWORK_YN]         VARCHAR (1)  NULL,
    [REWORK_SNO]        INT          NULL,
    [WORK_SEQ]          INT          NULL,
    [REGISTER]          VARCHAR (20) NULL,
    [REG_DDTT]          DATETIME     NULL,
    [MODIFIER]          VARCHAR (20) NULL,
    [MOD_DDTT]          DATETIME     NULL,
    CONSTRAINT [PK_TB_RL_TM_TRACKING] PRIMARY KEY CLUSTERED ([HEAT_NO] ASC, [HEAT_SEQ] ASC)
);

