CREATE TABLE [dbo].[TB_SHT_WR] (
    [HEAT_NO]                 VARCHAR (6)  NOT NULL,
    [HEAT_SEQ]                INT          NOT NULL,
    [REWORK_SNO]              INT          NOT NULL,
    [STEEL]                   VARCHAR (10) NULL,
    [ITEM]                    VARCHAR (2)  NULL,
    [ITEM_SIZE]               VARCHAR (4)  NULL,
    [STEEL_TYPE]              VARCHAR (3)  NULL,
    [MFG_DATE]                VARCHAR (8)  NULL,
    [QR_SCAN_INFO]            VARCHAR (16) NULL,
    [WORK_DATE]               VARCHAR (8)  NULL,
    [SHT_START_DDTT]          DATETIME     NULL,
    [SHT_END_DDTT]            DATETIME     NULL,
    [ROLLER_CONVR_SPEED]      NUMERIC (5)  NULL,
    [IMPELLER_NO1_SPEED]      NUMERIC (5)  NULL,
    [IMPELLER_NO2_SPEED]      NUMERIC (5)  NULL,
    [IMPELLER_NO3_SPEED]      NUMERIC (5)  NULL,
    [IMPELLER_NO4_SPEED]      NUMERIC (5)  NULL,
    [ROLLER_CONVR_SPEED_SETV] NUMERIC (5)  NULL,
    [IMPELLER_NO1_SPEED_SETV] NUMERIC (5)  NULL,
    [IMPELLER_NO2_SPEED_SETV] NUMERIC (5)  NULL,
    [IMPELLER_NO3_SPEED_SETV] NUMERIC (5)  NULL,
    [IMPELLER_NO4_SPEED_SETV] NUMERIC (5)  NULL,
    [REWORK_YN]               VARCHAR (1)  NULL,
    [REGISTER]                VARCHAR (20) NULL,
    [REG_DDTT]                DATETIME     NULL,
    [MODIFIER]                VARCHAR (20) NULL,
    [MOD_DDTT]                DATETIME     NULL,
    CONSTRAINT [PK_TB_SHT_WR] PRIMARY KEY CLUSTERED ([HEAT_NO] ASC, [HEAT_SEQ] ASC, [REWORK_SNO] ASC)
);

