CREATE TABLE [dbo].[TB_SHT_DUST_INFO] (
    [WORK_DDTT]                  DATETIME       NOT NULL,
    [DUST_On_TR]                 DATETIME       NULL,
    [DUST_Off_TR]                DATETIME       NULL,
    [Bag_BEF_STATICP]            NUMERIC (7, 2) NULL,
    [INH_TEMP]                   NUMERIC (6, 1) NULL,
    [Screw_Conveyor_STAT]        INT            NULL,
    [Screw_Conveyor_ABNORM_STAT] INT            NULL,
    [Rotary_Valve_STAT]          INT            NULL,
    [Rotary_Valve_ABNORM_STAT]   INT            NULL,
    [Vibrator_STAT]              INT            NULL,
    [Vibrator_ABNORM_STAT]       INT            NULL,
    [Pulse_Controller_STAT1]     INT            NULL,
    [Pulse_Controller_STAT2]     INT            NULL,
    [Pulse_Controller_STAT3]     INT            NULL,
    [Pulse_Controller_STAT4]     INT            NULL,
    [Pulse_Controller_STAT5]     INT            NULL,
    [Pulse_Controller_STAT6]     INT            NULL,
    [Pulse_Controller_STAT7]     INT            NULL,
    [Pulse_Controller_STAT8]     INT            NULL,
    [Pulse_Controller_STAT9]     INT            NULL,
    [Pulse_Controller_STAT10]    INT            NULL,
    [Pulse_Controller_STAT11]    INT            NULL,
    [Pulse_Controller_STAT12]    INT            NULL,
    [Pulse_Controller_STAT13]    INT            NULL,
    [DEF_PRES]                   NUMERIC (6, 1) NULL,
    [OPRN_RT]                    NUMERIC (6, 1) NULL,
    [SETV]                       NUMERIC (6, 1) NULL,
    [LOAD_BRG_TEMP]              NUMERIC (6, 1) NULL,
    [H_LOAD_BRG_TEMP]            NUMERIC (6, 1) NULL,
    [IVT_SPEED_SETV]             NUMERIC (6, 1) NULL,
    [LOAD_VIBR]                  NUMERIC (6, 1) NULL,
    [H_LOAD_VIBR]                NUMERIC (6, 1) NULL,
    [REGISTER]                   VARCHAR (20)   NULL,
    [REG_DDTT]                   DATETIME       NULL,
    [MODIFIER]                   VARCHAR (20)   NULL,
    [MOD_DDTT]                   DATETIME       NULL,
    CONSTRAINT [PK_TB_SHT_DUST_INFO] PRIMARY KEY CLUSTERED ([WORK_DDTT] ASC)
);



